version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run:
          name: "Install JFrog CLI"
          command: |
            curl -fL https://getcli.jfrog.io | sh
            # Configure Artifactory instance with JFrog CLI
            ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_PASSWORD --interactive false
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              rm -rf node_modules/
              ./jfrog rt npmi npm-virtual --build-name=circleci-npm-artifactory --build-number=$CIRCLE_BUILD_NUM
              ./jfrog rt bce circleci-npm-artifactory $CIRCLE_BUILD_NUM
              ./jfrog rt npmp npm-virtual --build-name=circleci-npm-artifactory --build-number=$CIRCLE_BUILD_NUM
              ./jfrog rt bp circleci-npm-artifactory $CIRCLE_BUILD_NUM
            fi
